name: CI

on:
  push:
    branches:
      - cleanroom
      - 'develop/**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, review_requested]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: CleanroomMC/Conventions/.github/workflows/build.yml@1.1.3
    with:
      release-branch: cleanroom
