name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: write
  issues: read
  pull-requests: read

jobs:
  release:
    uses: CleanroomMC/Conventions/.github/workflows/release.yml@1.1.3
    with:
      publish-maven: true
      publish-mods: true
    secrets: inherit
